language: java
jdk:
- oraclejdk12
before_script: cd Server
before_deploy: cp -r ../Client/ ./
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: "DoGnQuGiREZVXR0W2yoaUbPXqVSoeaa7vl2L2dE8yWm4VxGdE70KdQINdLdYV2FYQPKmuWMJIRdCtaqmcgi+kqU9/xtdqRAd3NOAs7yUH4BTwnP/IVouY8REuKsqo7wIuC0CiFGg32zryopcbapqACgzKYKOFOWD14AO/e5R5uBvLDFLQE5Fsr93ocFPqo83EdzbIh1kzOeGwiuBqyIyCmCFp6yzkwXsY32ffW2A4K5HcsSbA8FkmzTEnTv3vfeRjVcrQ/mZMaDg+dA8hNBU+LukkHk1+JC890rTFFpzK+Bxy+tNsy0ylFF7bjUfdatvKuNOeQIAKX+zH7pCA0k2s84+emqk73RysfVZyeSGUeChHwDqBXE8s8Ubp1U7ZzOxrVFboF96R5QPVZM8deoovRvqa73X1Lzb9V3ovRv+a/0NTLN1FWaq4EKhssajUDEOi2PUUMKhI9W7idrQlcNjDw4l//sgmcNP2gtwDi9IvPoFZiaQkYR6tbGCB5z3iaEcQKaQMfKHuznV7qCtnzBlLEZKVGUI/CAKOUcOoGn4afpNJCaigbX01/Y3SpolCVywk/uq6SJg9sKg84xbdenHzeFR3OXVBsRtRr7yjaoswhAsQ56dFd6eClrMra76aTrn0WcydR3RiH3g6IezhUwzip7Fa4wQ/LJhkz0WeSMUvus="
  app: rrgp
  skip_cleanup: true
  on:
    repo: leadpogrommer/rrgp
    branch: master
