language: java
jdk:
- oraclejdk12
before_script: cd Server
before_deploy: cp -r ../Client/ ./
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: "ZHeN6TKqcCeB9xstIrvgyTd8YV3yobIKaCh9fU+bbsE368qFn6e2q9n3v4D+kwkVYF6EyKZVmoVUfbICXEwaADa1YzhveGYqsuLvctoU1PfB7qlGSWXZ3CDTcyDarGfHzSZtuOafIzs1Q0kMacmyUPNn/ZdSttRZS4ReacwKDpsq3Ilu6UxUvXIgUUR98Ak1pK+uiB6fTSWDb4hRaUqd3smlTewMTYsXPGYOUk/suIMfMwkudJuN+l3smNJkzHkTxepImfy39QFddXz02E4xJlQnJBKNz/13LGBjEElF1L+6/AgOeLdjNlYe93GmBiox7nSf/GwzsAMGhkQ4R59gtE8QGrq6YLmYQ8nXzDLIlIKSwgXHj5J02TJlnpv1vSgangejEwXCNKcMdQ0L0nUGGaEXu2zzMZvVhP/qC9dRumBfWlbl9jHSwsyYYZEf3YRfa/YLgLeN5bgmg8+jMXEhOp2j1w74Oj32SIO7enp4WwfQxhNAx2OBTvhFAzjgVxOqbv9Zj7CCCeOGJ1m6pVDpqrWHJBRu0FaJivIjUiDkvnXcWjQ9yy3PKoQLJlsV1ZG0fvr79zjsKlKYekeNcxvMgQfwPXPiz75im/S4RChVCumn333KV+X0buzIHzg8dByuNZHhh8kBFi32yTbnRO2FxiBIKrL11VpLD/Uv7c4HB6U="
  app: rrgp
  skip_cleanup: true
  on:
    repo: leadpogrommer/rrgp
    branch: master
